# はじめる前に {-#introintro}

## おことわり {-}

本書は，プレゼミに参加している2年生を読者として想定しています．計量分析について彼らが何も知らないと仮定した上で，短い期間で「回帰分析についてなんとなく理解して計量分析の論文がなんとか読める」ようにすることおよび「自分自身でもなんちゃって重回帰分析ができる」ようにすることを本書は目的としています．厳密な理解よりも，直感的な(ふわっとした？)わかりやすさを最優先したため，いくつかの説明は曖昧であったり，厳密でなかったりします．また，著者の知識も決して十分ではないため，それによる誤りも少なからず存在しているものと思われます．その点を理解した上で，本書をご利用なさるようにお願いします．なお，ゼミの学生により執筆されており，久米郁男教授は本書の内容についてなんら関与していません．**本書の誤りはすべて著者の学生に帰するものです**．

**本書はまだ執筆中のため頻繁に更新されます**ので，ご注意ください．また，明らかな誤りや明らかに不適切な記述などがありましたら，[Twitter: `@ritsu1997`](https://twitter.com/ritsu1997)までお知らせください．

追加コメント：本書のデータはすべてシミュレーションで作成した架空のものです.したがって，その分析結果自体には意味がありませんので，ご注意ください．やや非現実的なデータになっていますが，いずれもう少し現実的な架空データをシミュレーションでつくるか現実のデータを使うようにするかして，改善します．とりあえず，今期(2019年)のプレゼミに間に合うように作りました．

## 著者について {-}

**北川梨津**

これの著者1．[Twitter: `@ritsu1997`](https://twitter.com/ritsu1997)．特に何も受賞していないが，いつか受賞できるように頑張っている．早稲田大学政治経済学部経済学科．2019年4月に早稲田大学大学院経済学研究科進学予定．

**原健人**

これの著者2．政治計量テキスト分析に明るい．学部の卒業論文「熟議は誰の影響を受けるか」で[2019年度政治経済学会論文コンクール最優秀賞受賞](https://www.waseda.jp/fpse/pse/news/2020/02/01/11476/)．その論文を国際シンポジウム[「熟議民主主義の実践と実験」](https://www.waseda.jp/inst/sgu/news/2020/02/07/7297/)で発表した．早稲田大学政治経済学部国際政治経済学科．2019年4月に早稲田大学大学院経済学研究科進学予定．



